<a href="https://colab.research.google.com/github/EDUART-Bloem/114-2-Programming-Language/blob/main/HW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [ ]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1-LBvMluvrbeiM2Zq4mKAldT80jf-o8fEuOmqarLH2xM/edit?usp=sharing')

In [ ]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('記帳本').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期    時間  分類  品項   錢  誰   哪   方式 備註
0  2026-03-05  8:00      捷運  30
1  2026-03-05  8:00      捷運  30
2  2026-03-05  8:00  通勤   運  30  我  捷運  悠遊卡  0
3  2026-03-05  8:00      捷運  30
4  2026-03-05  8:00      捷運  30

In [ ]:
import datetime

In [ ]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))

請輸入日期 (格式：YYYY-MM-DD): 2026-02-01
請輸入時間 (格式：HH:MM): 00:00
請輸入品項: STREET FIGHTER 6!
請輸入金額: 1000

In [ ]:
date_str

'2026-02-01'

In [ ]:
time_str

'00:00'

In [ ]:
item

'STREET FIGHTER 6!'

In [ ]:
amount

1000.0

In [ ]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類':'遊戲',
    '品項': item,
    '錢': amount,
    '誰':'我',
    '哪':'家',
    '方式':'信用卡',
    '備註':'-',

}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [ ]:
# 將 DataFrame 中的所有 NaN 值替換為 0
df = df.fillna(0)

# 顯示 DataFrame 的前幾行以確認更改
df.head()

           日期    時間  分類  品項   錢  誰   哪   方式 備註
0  2026-03-05  8:00      捷運  30
1  2026-03-05  8:00      捷運  30
2  2026-03-05  8:00  通勤   運  30  我  捷運  悠遊卡  0
3  2026-03-05  8:00      捷運  30
4  2026-03-05  8:00      捷運  30

In [ ]:
df

            日期     時間  分類                 品項       錢  誰   哪   方式 備註
0   2026-03-05   8:00                     捷運      30
1   2026-03-05   8:00                     捷運      30
2   2026-03-05   8:00  通勤                  運      30  我  捷運  悠遊卡  0
3   2026-03-05   8:00                     捷運      30
4   2026-03-05   8:00                     捷運      30
5   2026-03-05   8:00  通勤                  運      30  我  捷運  悠遊卡  0
6   2026-03-05  10:00  通勤                大逆轉     300  我  捷運  悠遊卡  -
7   2026-03-05   8:00                     捷運      30
8   2026-03-05   8:00                     捷運      30
9   2026-03-05   8:00  通勤                  運      30  我  捷運  悠遊卡  0
10  2026-03-05   8:00                     捷運      30
11  2026-03-05   8:00                     捷運      30
12  2026-03-05   8:00  通勤                  運      30  我  捷運  悠遊卡  0
13  2026-03-05  10:00  通勤                大逆轉     300  我  捷運  悠遊卡  -
14  2026-01-01  20:00  遊戲            逆轉檢事1+2     500  我   家  信用卡  -
15  2026-01-01  20:30  遊戲              逆轉123     500  我   家  信用卡  -
16  2026-02-01  00:00  遊戲  STREET FIGHTER 6!  1000.0  我   家  信用卡  -

In [ ]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('記帳本')

# 第二步：只將 data_to_write 的最後一列資料寫入工作表
# 注意：data_to_write[-1] 是一個列表，append_rows 預期接收一個列表的列表，所以需要用 [] 包裹起來
worksheet.append_rows(values=[data_to_write[-1]], value_input_option='USER_ENTERED')
print("最新的一筆資料已成功寫入 Google 記帳本")

最新的一筆資料已成功寫入 Google 記帳本